export const styles = {
  root: {
    background: "#0A0F1E",
    color: "#F8FAFC",
    fontFamily: "'Inter', system-ui, sans-serif",
    minHeight: "100vh",
    position: "relative",
    overflowX: "hidden",
  },
  gridBg: {
    position: "fixed",
    inset: 0,
    backgroundImage: `
      linear-gradient(rgba(99,102,241,0.04) 1px, transparent 1px),
      linear-gradient(90deg, rgba(99,102,241,0.04) 1px, transparent 1px)
    `,
    backgroundSize: "48px 48px",
    pointerEvents: "none",
    zIndex: 0,
  },
  nav: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 100,
    padding: "0 24px",
    transition: "background 0.3s, backdrop-filter 0.3s, border-color 0.3s",
    borderBottom: "1px solid transparent",
  },
  navScrolled: {
    background: "rgba(10,15,30,0.85)",
    backdropFilter: "blur(16px)",
    borderColor: "rgba(99,102,241,0.15)",
  },
  navInner: {
    maxWidth: 1100,
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: 64,
  },
  logo: {
    fontSize: 22,
    fontWeight: 800,
    letterSpacing: "-0.5px",
    cursor: "pointer",
    color: "#F8FAFC",
  },
  navLinks: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  navLink: {
    background: "none",
    border: "none",
    color: "#94A3B8",
    fontSize: 14,
    fontFamily: "inherit",
    cursor: "pointer",
    padding: "6px 12px",
    borderRadius: 6,
    transition: "color 0.2s",
  },
  navCta: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    background: "#6366F1",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "8px 18px",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    textDecoration: "none",
    marginLeft: 8,
  },
  menuBtn: {
    background: "none",
    border: "none",
    color: "#F8FAFC",
    fontSize: 22,
    cursor: "pointer",
  },
  mobileMenu: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    paddingBottom: 12,
    borderTop: "1px solid rgba(99,102,241,0.15)",
    paddingTop: 8,
  },
  mobileLink: {
    background: "none",
    border: "none",
    color: "#94A3B8",
    fontSize: 15,
    fontFamily: "inherit",
    cursor: "pointer",
    textAlign: "left",
    padding: "10px 0",
  },
  hero: {
    position: "relative",
    zIndex: 1,
    maxWidth: 1100,
    margin: "0 auto",
    padding: "130px 24px 80px",
    display: "flex",
    alignItems: "center",
    gap: 60,
    flexWrap: "wrap",
  },
  heroContent: {
    flex: "1 1 340px",
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: "rgba(99,102,241,0.1)",
    border: "1px solid rgba(99,102,241,0.3)",
    color: "#A5B4FC",
    borderRadius: 20,
    padding: "5px 14px",
    fontSize: 13,
    fontWeight: 500,
    marginBottom: 24,
  },
  badgeDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    background: "#22C55E",
    boxShadow: "0 0 6px #22C55E",
  },
  heroName: {
    fontSize: "clamp(40px, 6vw, 72px)",
    fontWeight: 800,
    lineHeight: 1.05,
    letterSpacing: "-2px",
    margin: "0 0 16px",
    background: "linear-gradient(135deg, #F8FAFC 60%, #A5B4FC)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  heroRole: {
    fontFamily: "'Courier New', monospace",
    fontSize: "clamp(18px, 2.5vw, 26px)",
    fontWeight: 600,
    marginBottom: 20,
    letterSpacing: "0.5px",
  },
  heroDesc: {
    color: "#94A3B8",
    fontSize: 16,
    lineHeight: 1.7,
    maxWidth: 480,
    margin: "0 0 32px",
  },
  heroActions: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
    marginBottom: 24,
  },
  btnPrimary: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: "#6366F1",
    color: "#fff",
    borderRadius: 8,
    padding: "10px 22px",
    fontWeight: 700,
    fontSize: 14,
    textDecoration: "none",
    border: "none",
    transition: "background 0.2s, transform 0.15s",
  },
  btnOutline: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: "transparent",
    color: "#A5B4FC",
    border: "1.5px solid #6366F1",
    borderRadius: 8,
    padding: "10px 22px",
    fontWeight: 600,
    fontSize: 14,
    textDecoration: "none",
    transition: "background 0.2s",
  },
  btnGhost: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: "rgba(148,163,184,0.08)",
    color: "#94A3B8",
    border: "1px solid rgba(148,163,184,0.15)",
    borderRadius: 8,
    padding: "10px 16px",
    fontWeight: 500,
    fontSize: 14,
    textDecoration: "none",
  },
  edu: { marginTop: 4 },
  eduBadge: {
    color: "#64748B",
    fontSize: 13,
    fontWeight: 500,
  },
  statsBand: {
    position: "relative",
    zIndex: 1,
    maxWidth: 1100,
    margin: "0 auto",
    padding: "0 24px 20px",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: 16,
  },
  statCard: {
    background: "rgba(15,20,40,0.7)",
    border: "1px solid rgba(99,102,241,0.12)",
    borderRadius: 12,
    padding: "18px 20px",
    backdropFilter: "blur(6px)",
  },
  statValue: {
    fontSize: 26,
    fontWeight: 800,
    letterSpacing: "-0.5px",
    background: "linear-gradient(135deg, #A5B4FC, #6366F1)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  statLabel: {
    color: "#94A3B8",
    fontSize: 12.5,
    fontWeight: 500,
    marginTop: 4,
    letterSpacing: "0.3px",
  },
  highlights: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    gap: 12,
  },
  highlightRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    color: "#CBD5E1",
    fontSize: 14,
    lineHeight: 1.55,
    background: "rgba(99,102,241,0.05)",
    border: "1px solid rgba(99,102,241,0.1)",
    borderRadius: 10,
    padding: "14px 16px",
  },
  highlightCheck: {
    color: "#22C55E",
    fontWeight: 800,
    flexShrink: 0,
    marginTop: 1,
  },
  heroVisual: {
    flex: "1 1 300px",
    display: "flex",
    justifyContent: "center",
  },
  terminalCard: {
    background: "#0D1117",
    border: "1px solid rgba(99,102,241,0.2)",
    borderRadius: 14,
    overflow: "hidden",
    width: "100%",
    maxWidth: 400,
    boxShadow: "0 0 60px rgba(99,102,241,0.08)",
  },
  terminalBar: {
    background: "#161B22",
    padding: "10px 14px",
    display: "flex",
    alignItems: "center",
    gap: 6,
    borderBottom: "1px solid rgba(99,102,241,0.1)",
  },
  termDot: {
    width: 12,
    height: 12,
    borderRadius: "50%",
  },
  termTitle: {
    marginLeft: 8,
    color: "#475569",
    fontSize: 12,
    fontFamily: "monospace",
  },
  termBody: {
    padding: "18px 20px",
    fontFamily: "'Courier New', monospace",
    fontSize: 13,
    lineHeight: 1.8,
  },
  section: {
    position: "relative",
    zIndex: 1,
    maxWidth: 1100,
    margin: "0 auto",
    padding: "70px 24px",
  },
  sectionLabel: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 40,
  },
  sectionAccent: {
    color: "#6366F1",
    fontFamily: "monospace",
    fontSize: 22,
    fontWeight: 700,
  },
  sectionTitle: {
    fontSize: "clamp(26px, 4vw, 38px)",
    fontWeight: 800,
    letterSpacing: "-1px",
    margin: 0,
  },
  timeline: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  expCard: {
    background: "rgba(15,20,40,0.7)",
    border: "1px solid rgba(99,102,241,0.12)",
    borderRadius: 12,
    padding: "22px 24px",
    cursor: "pointer",
    transition: "border-color 0.2s",
    backdropFilter: "blur(6px)",
  },
  expHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  expHeaderLeft: {
    display: "flex",
    alignItems: "flex-start",
    gap: 14,
  },
  expIconWrap: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    height: 48,
    borderRadius: 10,
    flexShrink: 0,
    overflow: "hidden",
    background: "#fff",
    boxShadow: "0 2px 10px rgba(0,0,0,0.25)",
  },
  expLogo: {
    height: "100%",
    width: "auto",
    objectFit: "contain",
    display: "block",
  },
  expSummary: {
    color: "#94A3B8",
    fontSize: 13.5,
    lineHeight: 1.6,
    marginTop: 10,
    maxWidth: 620,
  },
  expCompany: {
    fontSize: 18,
    fontWeight: 800,
    letterSpacing: "-0.5px",
  },
  expTypeBadge: {
    background: "rgba(99,102,241,0.12)",
    color: "#A5B4FC",
    borderRadius: 5,
    padding: "2px 8px",
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.5px",
    textTransform: "uppercase",
  },
  expRole: {
    color: "#CBD5E1",
    fontWeight: 600,
    fontSize: 15,
    marginTop: 3,
  },
  expPeriod: {
    color: "#475569",
    fontSize: 13,
    marginTop: 3,
    fontFamily: "monospace",
  },
  expList: {
    margin: "18px 0 0",
    padding: 0,
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  expBullet: {
    display: "flex",
    color: "#94A3B8",
    fontSize: 14,
    lineHeight: 1.6,
  },
  projectGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
    gap: 20,
  },
  projectCard: {
    background: "rgba(15,20,40,0.7)",
    border: "1px solid rgba(99,102,241,0.12)",
    borderRadius: 12,
    padding: "24px",
    backdropFilter: "blur(6px)",
    transition: "border-color 0.2s, transform 0.2s",
  },
  projectTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  projectIcon: { fontSize: 24, color: "#A5B4FC", display: "flex" },
  projectLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    color: "#6366F1",
    fontSize: 13,
    fontWeight: 600,
    textDecoration: "none",
  },
  projectName: {
    fontSize: 17,
    fontWeight: 700,
    margin: "0 0 10px",
    letterSpacing: "-0.3px",
  },
  projectDesc: {
    color: "#94A3B8",
    fontSize: 14,
    lineHeight: 1.65,
    margin: "0 0 16px",
  },
  skillsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))",
    gap: 16,
  },
  skillGroup: {
    background: "rgba(15,20,40,0.7)",
    border: "1px solid rgba(99,102,241,0.12)",
    borderRadius: 12,
    padding: "20px",
    backdropFilter: "blur(6px)",
  },
  skillCat: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "1.5px",
    textTransform: "uppercase",
    color: "#6366F1",
    marginBottom: 12,
  },
  tagRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  },
  tag: {
    background: "rgba(99,102,241,0.1)",
    color: "#A5B4FC",
    border: "1px solid rgba(99,102,241,0.2)",
    borderRadius: 6,
    padding: "4px 10px",
    fontSize: 12,
    fontWeight: 500,
  },
  skillTag: {
    background: "rgba(99,102,241,0.08)",
    color: "#94A3B8",
    border: "1px solid rgba(99,102,241,0.15)",
    borderRadius: 6,
    padding: "5px 11px",
    fontSize: 13,
    fontWeight: 500,
    cursor: "default",
    transition: "background 0.2s, color 0.2s, border-color 0.2s, box-shadow 0.2s",
  },
  skillTagHov: {
    background: "rgba(99,102,241,0.2)",
    color: "#C7D2FE",
    borderColor: "#6366F1",
    boxShadow: "0 0 12px rgba(99,102,241,0.25)",
  },
  achieveGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
    gap: 16,
  },
  achieveCard: {
    background: "rgba(15,20,40,0.7)",
    border: "1px solid rgba(99,102,241,0.12)",
    borderRadius: 12,
    padding: "22px 24px",
    display: "flex",
    alignItems: "flex-start",
    gap: 16,
    backdropFilter: "blur(6px)",
  },
  achieveIcon: { fontSize: 28, lineHeight: 1 },
  achieveTitle: { fontWeight: 700, fontSize: 15, marginBottom: 4 },
  achieveDesc: { color: "#94A3B8", fontSize: 13, lineHeight: 1.5 },
  footer: {
    position: "relative",
    zIndex: 1,
    borderTop: "1px solid rgba(99,102,241,0.1)",
    padding: "24px",
  },
  footerInner: {
    maxWidth: 1100,
    margin: "0 auto",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 12,
  },
};
